### ISSUE TITLE
MacOS: crash if manual theme selection in Demo

### ISSUE THREAD

**Issue by macdeport** [definite-d/PSG_Reskinner#1]
```python 
Traceback (most recent call last):
  File "/var/folders/0d/dj43zrpj3kg85hdt91_cjwy00000gp/T/BBEditRunTemp-untitled text 57.py", line 47, in <module>
    reskin(window)
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/psg_reskinner/__main__.py", line 84, in reskin
    window.TKroot.config(background=theme_background_color())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "1234567890"

```

**Comment by definite-d** [comment]
This is a PySimpleGUI issue, and it's already been reported and fixed in v4.61.1.59 as seen in PySimpleGUI/PySimpleGUI/#5686
