### ISSUE TITLE
TabGroups / Tabs seem to break the 'reskin' command.

### ISSUE THREAD

**Issue by richnanney** [definite-d/PSG_Reskinner#8]
I'll be using the same code as my previous issue just for demonstration purposes.

```python
import PySimpleGUI as sg
from random import randrange
import psg_reskinner as psgr

unsafe_themes = [
    "SystemDefaultForReal",
    "Default1",
    "Default",
    "SystemDefault",
    "DefaultNoMoreNagging",
    "SystemDefault1",
    "GrayGrayGray",
]


def randomize_theme():
    new_theme = sg.theme_list()[randrange(0, 154)]
    while new_theme in unsafe_themes:
        new_theme = sg.theme_list()[randrange(0, 154)]
    return new_theme



layout = [
    [sg.T("Hello world!")],
    [sg.B("Randomize Theme"), sg.B("Exit")]
]

window = sg.Window("Random Themes", layout=layout)
while True:
    event, values = window.read(300)

    if event == sg.WIN_CLOSED or event == "Exit":
        break

    if event == "Randomize Theme":
        new_theme = randomize_theme()
        psgr.reskin(
            window=window,
            new_theme=new_theme,
            theme_function=sg.theme,
            lf_table=sg.LOOK_AND_FEEL_TABLE,
        )
```

Using this code, a small window pops up and clicking the button randomizes the theme to be any of the 'safe' themes within PSG. That's all well and good, but if I were to add a tabgroup in there...

```python
...
tab_layout = [[sg.T("Goodbye!")]]
layout = [
    [sg.T("Hello world!")],
    [sg.B("Randomize Theme"), sg.B("Exit")],
    [sg.TabGroup(
        [[sg.Tab(title="tab", layout=tab_layout)]]
        )
    ],
]
```
The build will compile and launch, but upon pressing the 'randomize theme' button I get the following traceback:
```
Traceback (most recent call last):
  File "c:\...\theme_testing.py", line 43, in <module>
    psgr.reskin(
  File "C:\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\psg_reskinner\__main__.py", line 416, in reskin
    _recurse_menu(element.TKRightClickMenu, new_theme_dict['TEXT_INPUT'], new_theme_dict['INPUT'])
  File "C:\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\psg_reskinner\__main__.py", line 332, in _recurse_menu
    for index in range(0, tkmenu.index('end') + 1):
                          ~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Which I can only assume is due to the addition of the tabgroup. This assumption could be wrong, of course, in which case I would welcome correction -- which is why I am offering the entire code here in case it's an error on my end.

**Comment by definite-d** [comment]
Fixed from v2.3.13, which is up on PyPi for download.
